version: '3.8'

services:
  backend:
    build:
      context: ./shared-expenses-api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./shared-expenses-api:/app
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped 
