name: Deploy to Production
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  infra-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Cachix
        run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install &> /dev/null
      - name: Use Cachix
        run: |
          cachix use fluidattacks
      - name: Load Age private key
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
      - name: Deploy Infrastructure
        run: |
          nix run .#infra -- apply
      - name: Cleanup secrets
        if: always()
        run: "rm -f ~/.config/sops/age/keys.txt || true \n"
