name: Deploy to Production
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  infra-apply:
    outputs:
      public_api_url: ${{ steps.infra-apply.outputs.public_api_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Load Age private key
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
      - name: Deploy Infrastructure
        run: |
          nix run .#infra -- apply
      - name: Cleanup secrets
        if: always()
        run: "rm -f ~/.config/sops/age/keys.txt || true \n"
  front-deploy:
    runs-on: ubuntu-latest
    env:
      PUBLIC_API_URL: ${{ needs.infra-apply.outputs.public_api_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable\
      - name: Load Age private key
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
      - name: Deploy Frontend
        run: |
          nix run .#front-deploy
  api-push-container:
    needs: infra-apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable\
      - name: Load Age private key
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
      - name: Push API container
        run: |
          nix run .#api-container-push
