name: CI
on:
  push:
    branches-ignore:
      - main
jobs:
  api-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run api lint
        run: |
          nix run .#api-lint
  infra-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Load Age private key
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
      - name: Run infra plan
        run: |
          nix run .#infra -- plan
      - name: Cleanup secrets
        if: always()
        run: "rm -f ~/.config/sops/age/keys.txt || true \n"
